### ISSUE TITLE
request response object unavailable in celery tasks, non-default values raises errors

### ISSUE THREAD

**Issue by ashiqYousuf** [sh-cho/django-custom-logging#2]
Hi @sh-cho , I hope you are doing well. To the point, We have integrated your logging module in our company products, we have 2 products crm and apis, in apis there is are no celery tasks but in crm there's a more heavy lifting going in these tasks.

Now as you know whatever is available in our apis isn't in our celery utilities (Ex request object).

request object is very critical for any api as we can log everything from this, user details, request params, request data, user address and so on. When we start replacing our monotonous prints with logger.info || logger.error soon celery server started breaking. After a day of chaos, I when closely looked into your package (thanks for having this) I saw default values are not yet handled here.

So I have resolved this issue into my product by modifying your package for our personal use. So I want to let you know if i can contribute to this issue. It would be a great to hear from you soon.

You can assign the default values issue to me and I'll try to raise the pull request as early as possible.

Thanks

**Comment by sh-cho** [comment]
@ashiqYousuf Hi, Thanks for the report!
Since I haven't used django a while, I need to take some time to digest 😅
Give me a moment please.

**Comment by ashiqYousuf** [comment]
@sh-cho thanks for the reply, I have resolved that issue and raised a PR, please have a look into it.
